# Generated by Django 5.2.9 on 2025-12-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='frequency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
